version: "3.7"

services:
  app:
    image: ghcr.io/pedrogwe/govix-lp:latest
    networks:
      - mandatto
      - Vidrofy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"

        # Governanc LP — www.governanc.com.br
        - "traefik.http.routers.govix-lp.rule=Host(`www.governanc.com.br`)"
        - "traefik.http.routers.govix-lp.entrypoints=websecure"
        - "traefik.http.routers.govix-lp.tls=true"
        - "traefik.http.routers.govix-lp.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.govix-lp.loadbalancer.server.port=80"

        # Governanc LP — governanc.com.br (sem www)
        - "traefik.http.routers.govix-lp-apex.rule=Host(`governanc.com.br`)"
        - "traefik.http.routers.govix-lp-apex.entrypoints=websecure"
        - "traefik.http.routers.govix-lp-apex.tls=true"
        - "traefik.http.routers.govix-lp-apex.tls.certresolver=letsencryptresolver"
        - "traefik.http.routers.govix-lp-apex.service=govix-lp"

networks:
  mandatto:
    external: true
    name: mandatto
  Vidrofy:
    external: true
    name: Vidrofy
